### ISSUE TITLE
Spyne 2.12.15 Breaks Tests

### ISSUE THREAD

**Issue by pglombardo** [instana/python-sensor#118]
Recently released Spyne is causing [these Travis tests](https://travis-ci.org/instana/python-sensor/builds/471220759) to fail:
```
Collecting spyne>=2.9 (from instana==1.8.7->-r requirements-test.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/cb/73/67e489bdfdf8ed9f927001595a1e57891b12e580fcfa9aa64b3c4df16a8a/spyne-2.12.15.tar.gz (439kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kxoz8746/spyne/setup.py", line 51, in <module>
        LONG_DESC += u"\n\n" + open('CHANGELOG.rst', 'r').read().decode('utf8')
    AttributeError: 'str' object has no attribute 'decode'
```
Spyne is used in the test suite and not a general dependency in normal installs.

Limited the version for the time being.

**Comment by pglombardo** [comment]
Spyne/sudsjurko has been version limited in the test suite to the supported version.
