### ISSUE TITLE
Flask: -m flask run breaks with sensor; `flask run` works

### ISSUE THREAD

**Issue by pglombardo** [instana/python-sensor#88]
```
(DemoFlask) Hughs-MacBook-Pro:DemoFlask hughbrien$ python -m flask run
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)
AttributeError: '_ImportHookChainedLoader' object has no attribute 'get_code'
```

**Comment by pglombardo** [comment]
Tested with latest version and this now has been fixed:

<img width="1515" alt="screen shot 2019-03-01 at 11 33 58" src="https://user-images.githubusercontent.com/395132/53632788-13c2ee80-3c16-11e9-8738-cd8db6c69a70.png">
